In [1]:
import pandas as pd

In [2]:
# trip count for every company from 15th to 16th November 2017
company_count_df = pd.read_csv('data/project_sql_result_01.csv')

# average trips per day that ended in every neighbourhood in November
dropoff_count_df = pd.read_csv('data/project_sql_result_04.csv')

# weather conditions and trip duration for trips from Loop to O'Hare Airport
weather_df = pd.read_csv('data/project_sql_result_07.csv')

### 1 - Cleaning

#### 1.1 - company_count_df

In [3]:
company_count_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64 entries, 0 to 63
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   company_name  64 non-null     str
 1   trips_amount  64 non-null     int64
dtypes: int64(1), str(1)
memory usage: 1.1 KB

In [4]:
company_count_df['company_name'] = (company_count_df['company_name']
                                    .str.lower()
                                    .str.strip()
)

In [5]:
# check for duplicated company names
company_count_df[company_count_df['company_name'].duplicated()]

Empty DataFrame
Columns: [company_name, trips_amount]
Index: []

There are 64 company names and there is no duplicated value.

#### 1.2 - dropoff_count_df

In [6]:
dropoff_count_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 94 entries, 0 to 93
Data columns (total 2 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   dropoff_location_name  94 non-null     str
 1   average_trips          94 non-null     float64
dtypes: float64(1), str(1)
memory usage: 1.6 KB

In [8]:
dropoff_count_df['dropoff_location_name'] = (
    dropoff_count_df['dropoff_location_name']
    .str.lower()
    .str.strip()
)

In [10]:
dropoff_count_df[dropoff_count_df['dropoff_location_name'].duplicated()]

Empty DataFrame
Columns: [dropoff_location_name, average_trips]
Index: []

There are 94 dropoff locations and there is no duplicated value.

#### 1.3 - weather_df